# Generated by Django 5.2.6 on 2025-09-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='имя пользователя')),
                ('surname', models.CharField(max_length=20, verbose_name='фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('phone', models.CharField(max_length=15, verbose_name='номер телефона')),
                ('password', models.CharField(max_length=20, verbose_name='пароль')),
            ],
            options={
                'verbose_name': 'пользователя',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
