# Generated by Django 5.2.6 on 2025-09-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(max_length=20, verbose_name='артикул')),
                ('name', models.CharField(max_length=50, verbose_name='полное название')),
                ('quantity', models.IntegerField(verbose_name='Колличесво')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('disk_type', models.CharField(max_length=20, verbose_name='Тип диска')),
                ('manufacturer', models.CharField(max_length=20, verbose_name='брэнд')),
                ('model', models.CharField(blank=True, max_length=20, null=True, verbose_name='модель')),
                ('width', models.FloatField(verbose_name='Ширина диска(B)')),
                ('diameter', models.FloatField(verbose_name='Диаметр диска(D)')),
                ('bolts', models.IntegerField(verbose_name='Кол-во отверстий')),
                ('et', models.FloatField(verbose_name='Вылет(et,мм)')),
                ('pcd', models.FloatField(verbose_name='PCD(межболтовое расст)')),
                ('dia', models.FloatField(verbose_name='Центральное отверстие(DIA, мм)')),
                ('color', models.CharField(max_length=100, verbose_name='цвет')),
                ('img', models.URLField(blank=True, null=True, verbose_name='ссылка на фото')),
            ],
            options={
                'verbose_name': 'диск',
                'verbose_name_plural': 'диски',
            },
        ),
    ]
