# Generated by Django 5.2.6 on 2025-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='art',
            field=models.CharField(max_length=50, verbose_name='артикул'),
        ),
    ]
