# Generated by Django 5.2.6 on 2025-09-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0002_alter_disk_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='art',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='артикул'),
        ),
    ]
