# Generated by Django 5.2.6 on 2025-09-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0003_alter_disk_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='name',
            field=models.CharField(max_length=200, verbose_name='полное название'),
        ),
    ]
