# Generated by Django 5.2.6 on 2025-09-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0004_alter_disk_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='модель'),
        ),
    ]
