# Generated by Django 5.2.6 on 2025-09-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0005_alter_disk_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='name',
            field=models.CharField(max_length=255, verbose_name='полное название'),
        ),
    ]
