# Generated by Django 5.2.6 on 2025-09-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0006_alter_disk_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='disk_type',
            field=models.CharField(max_length=100, verbose_name='Тип диска'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='брэнд'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='модель'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='quantity',
            field=models.IntegerField(verbose_name='Колличество'),
        ),
    ]
