# Generated by Django 5.2.6 on 2025-09-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(max_length=32, unique=True, verbose_name='артикул')),
                ('name', models.CharField(max_length=150, verbose_name='полное название')),
                ('quantity', models.IntegerField(verbose_name='количество')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='бренд')),
                ('model', models.CharField(max_length=50, verbose_name='модель')),
                ('season', models.CharField(max_length=10, verbose_name='сезон')),
                ('width', models.IntegerField(verbose_name='ширина')),
                ('height', models.IntegerField(verbose_name='высота')),
                ('radius', models.IntegerField(verbose_name='радиус')),
                ('speed_index', models.CharField(max_length=20, verbose_name='индекс скорости')),
                ('load_index', models.CharField(max_length=20, verbose_name='индекс нагрузки')),
                ('year', models.IntegerField(verbose_name='год производства')),
                ('thorns', models.BooleanField(default=False, verbose_name='шипы')),
                ('protection', models.CharField(blank=True, max_length=50, null=True, verbose_name='защита обода')),
                ('sale', models.BooleanField(default=False, verbose_name='распродажа')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='ссылка на фото')),
            ],
            options={
                'verbose_name': 'шина',
                'verbose_name_plural': 'шины',
            },
        ),
    ]
