# Generated by Django 5.2.6 on 2025-09-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='load_index',
            field=models.CharField(max_length=50, verbose_name='индекс нагрузки'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='speed_index',
            field=models.CharField(max_length=50, verbose_name='индекс скорости'),
        ),
    ]
