# Generated by Django 5.2.6 on 2025-09-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0002_alter_tire_load_index_alter_tire_speed_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='art',
            field=models.CharField(max_length=32, verbose_name='артикул'),
        ),
    ]
