# Generated by Django 5.2.8 on 2025-11-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0003_alter_tire_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='protection',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='sale',
        ),
    ]
