# Generated by Django 5.2.8 on 2025-11-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0004_remove_tire_protection_remove_tire_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='year',
        ),
    ]
