# Generated by Django 5.2.8 on 2025-11-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0005_remove_tire_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='art',
            field=models.CharField(max_length=32, null=True, verbose_name='артикул'),
        ),
    ]
