# Generated by Django 5.2.6 on 2025-10-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(max_length=32, verbose_name='артикул')),
                ('brand', models.CharField(max_length=50, verbose_name='бренд')),
                ('model', models.CharField(max_length=50, verbose_name='модель')),
                ('name', models.CharField(max_length=150, verbose_name='полное название')),
                ('count', models.IntegerField(verbose_name='количество')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('length', models.IntegerField(verbose_name='длина')),
                ('width', models.IntegerField(verbose_name='ширина')),
                ('height', models.IntegerField(verbose_name='высота')),
                ('container', models.IntegerField(verbose_name='емкость')),
                ('start_current', models.IntegerField(verbose_name='пусковой ток')),
                ('polarity', models.CharField(max_length=10, verbose_name='полярность')),
                ('weight', models.CharField(max_length=50, verbose_name='вес')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='ссылка на фото')),
            ],
            options={
                'verbose_name': 'аккумулятор',
                'verbose_name_plural': 'аккумуляторы',
            },
        ),
    ]
