# Generated by Django 5.2.1 on 2025-12-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_updated_at_alter_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_art',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Артикул'),
        ),
    ]
