# Generated by Django 5.2.1 on 2025-12-02 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Позиция в корзине', 'verbose_name_plural': 'Позиции в корзине'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='basket.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_id',
            field=models.PositiveIntegerField(verbose_name='ID товара'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_type',
            field=models.CharField(choices=[('tire', 'Шина'), ('disk', 'Диск'), ('akb', 'Аккумулятор')], max_length=10, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
